# @name="puppetter"
GET http://localhost:3000/


###
# @params site="required"
# @params script="а"
#
#
# @name="POST request"
POST http://localhost:3000/scrape
Content-Type: text/html




### GET jobs
# @name="get_jobs"

GET http://localhost:80/api/jobs


### Create new job (failed)
# @name="create job"

POST http://localhost:80/api/job/create
Content-Type: text/json

[]


