framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            redis:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                # default configuration
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 16000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 1
                    max_delay: 0

            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'


        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\TelegramNotification': redis

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
