nelmio_api_doc:
    documentation:
        info:
            title: Publisher Api
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api except /api/doc
            - ^/bot
